# Project name (must match the one in CMakeLists.txt)
PROJECT_NAME = VulkanPlayground

# Directory containing the CMakeLists.txt and project sources, relative to this Makefile
CMAKE_PROJECT_SUBDIR = .

# Name of the build directory (will be created inside CMAKE_PROJECT_SUBDIR)
BUILD_DIR_NAME = build

# Full path to the build directory
BUILD_DIR = $(CMAKE_PROJECT_SUBDIR)/$(BUILD_DIR_NAME)

# Path to the final executable
EXECUTABLE = $(BUILD_DIR)/$(PROJECT_NAME)

# Set the build type (default to Release if not specified via command line e.g., make BUILD_TYPE=Debug)
BUILD_TYPE ?= Release

.PHONY: all configure build run clean debug release rebuild shader_clean

# Default target
all: build

# Configure the project using CMake
# Creates the build directory and generates build files (e.g., Makefiles) within it.
configure:
	@echo "+++ Configuring $(PROJECT_NAME) for $(BUILD_TYPE) in $(BUILD_DIR) +++"
	@mkdir -p $(BUILD_DIR)
	@cmake -S $(CMAKE_PROJECT_SUBDIR) -B $(BUILD_DIR) -DCMAKE_BUILD_TYPE=$(BUILD_TYPE)

# Build the project using the generated build files
# CMake will now also handle shader compilation due to changes in CMakeLists.txt
build:
	@echo "+++ Building $(PROJECT_NAME) ($(BUILD_TYPE)) +++"
	@# Ensure configuration has run.
	@if [ ! -f "$(BUILD_DIR)/Makefile" ] && [ ! -f "$(BUILD_DIR)/build.ninja" ]; then \
		$(MAKE) configure BUILD_TYPE=$(BUILD_TYPE); \
	fi
	@cmake --build $(BUILD_DIR)

# Run the compiled executable
run: build
	@echo "+++ Running $(PROJECT_NAME) +++"
	@$(EXECUTABLE)

# Clean build files generated by CMake and our custom shader outputs
clean: shader_clean # Keep shader_clean if you want to explicitly clean .spv files
	@echo "+++ Cleaning CMake build directory: $(BUILD_DIR) +++"
	@rm -rf $(BUILD_DIR)

# Clean only shader files (useful if they are in the source directory)
# If shaders are output to the build directory, 'make clean' would get them.
# This target is mainly useful if .spv files are alongside .vert/.frag sources.
shader_clean:
	@echo "+++ Cleaning shaders in $(CMAKE_PROJECT_SUBDIR)/shaders/ +++"
	@rm -f $(CMAKE_PROJECT_SUBDIR)/shaders/*.spv

# Rebuild the project (clean then build all)
rebuild: clean all

# Debug mode: Clean, re-configure for Debug, then build
debug:
	$(MAKE) clean
	$(MAKE) configure BUILD_TYPE=Debug
	$(MAKE) build

# Release mode: Clean, re-configure for Release, then build
release:
	$(MAKE) clean
	$(MAKE) configure BUILD_TYPE=Release
	$(MAKE) build